require('./account').sync({force: true})
require('./contact').sync({force: true})
require('./customer').sync({force: true})
require('./customer_type').sync({force: true})
require('./delivery').sync({force: true})
require('./order').sync({force: true})
require('./pricing').sync({force: true})